### ISSUE TITLE
A2OS Weekly 标准化工作流

### ISSUE THREAD

**Issue by Triple-Z** [NUAA-Open-Source/A2OS#5]
- 每周四确定讲者及主题；
- 每周五发出通知并确定场地；
- 周末如期开展 `A2OS Weekly`。

## A2OS 的义务

- 周三之前邀请好讲者；
- 周四之前确定好主题；
- 将讲座需要的预备知识发布到 [FTP][] 上；
- 更新 `历次培训及讲座` 文件，添加预备知识[^1]；
- 周五之前预定好场地；
- 更新 `历次培训及讲座` 文件，添加归档文件[^1]。

## 讲者的义务

- 周四之前确定好讲座主题；
- 周五之前在 [A2OS 主邮件列表][ML]中发布讲座信息，需要包括以下几点内容：
  - 讲座主题；
  - 讲座内容；
  - 讲座面向对象及先修知识要求；
  - 讲座时间、地点、讲者名称。
- 将先序文档提交给 `A2OS` 发布[^1]；
- 将后序文档提交给 `A2OS` 发布[^1]。
- ~~向本项目提 [PR][]，修改 `历次培训与讲座` 文件，添加先序文档（论文等）[^2]；~~
- ~~向本项目提 [PR][]，修改 `历次培训与讲座` 文件，添加后序文档（幻灯片等）[^2]。~~

[FTP]: https://ftp.a2os.club/
[ML]: https://groups.google.com/group/a2os-general
[PR]: https://help.github.com/articles/about-pull-requests/

若 [FTP][] 支持自主上传，则 [^1] 任务改为 [^2] 任务。

**Comment by villivateur** [comment]
ftp.a2os.club正在优化中，很快即可自主上传

**Comment by Triple-Z** [comment]
close due to inactivity.
